concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: github.event_name == 'pull_request_target'
      name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: refs/pull/${{ github.event.number }}/merge
    - continue-on-error: true
      if: github.event_name == 'push'
      name: Checkout code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v3.0.0
    - continue-on-error: true
      name: Build
      run: 'mvn --batch-mode --no-transfer-progress install -DskipTests -Pe2e -Pdocker-testsuite
        -Ptests-docker -Dhawtio-container -pl :hawtio-test-suite,:hawtio-tests-quarkus,:hawtio-tests-springboot
        -am

        '
    - continue-on-error: true
      name: Export docker images
      run: 'mkdir -p /tmp/images/

        docker save hawtio-test-suite:${{ matrix.java }} > /tmp/images/hawtio-test-suite-${{
        matrix.java }}.tar

        docker save hawtio-quarkus-app:${{ matrix.java }} > /tmp/images/hawtio-quarkus-app-${{
        matrix.java }}.tar

        docker save hawtio-springboot-app:${{ matrix.java }} > /tmp/images/hawtio-springboot-app-${{
        matrix.java }}.tar

        '
    - continue-on-error: true
      name: Cache images
      uses: actions/cache/save@v4
      with:
        key: e2e-docker-images-${{ matrix.java }}-${{ github.run_id }}-${{ github.run_attempt
          }}
        path: /tmp/images
    strategy:
      fail-fast: false
      matrix:
        java:
        - '17'
        - '21'
  publish-results:
    if: always()
    needs: test
    permissions:
      actions: read
      checks: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Download Test Results
      uses: actions/download-artifact@v3
      with:
        name: test-results
        path: test-results
    - continue-on-error: true
      if: always()
      name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: '**/Cucumber.xml

          '
        json_file: results.json
    - continue-on-error: true
      name: Install xmllint
      run: sudo apt-get install -y xmlstarlet jq
    - continue-on-error: true
      name: Generate summary
      run: 'export CHECK_URL=$(jq -r .check_url results.json)

        bash tests/hawtio-test-suite/process_test_results.sh test-results > summary.md

        '
    - continue-on-error: true
      name: Update summary
      run: 'cat summary.md >> $GITHUB_STEP_SUMMARY

        '
    - continue-on-error: true
      id: generate-token
      if: github.event_name == 'pull_request_target'
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ secrets.HAWTIO_CI_APP_ID }}
        private_key: ${{ secrets.HAWTIO_CI_PRIVATE_KEY }}
    - continue-on-error: true
      if: github.event_name == 'pull_request_target'
      name: Comment PR with summary
      uses: thollander/actions-comment-pull-request@v2
      with:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        comment_tag: execution
        filePath: summary.md
  test:
    env:
      REPORT_DIR: results-${{matrix.runtime}}-${{matrix.java}}-${{matrix.browser}}
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v3.0.0
    - continue-on-error: true
      name: Download images
      uses: actions/cache/restore@v4
      with:
        key: e2e-docker-images-${{ matrix.java }}-${{ github.run_id }}-${{ github.run_attempt
          }}
        path: /tmp/images
    - continue-on-error: true
      name: Load images
      run: "for i in /tmp/images/*.tar; do\n  docker load --input $i\ndone\n"
    - continue-on-error: true
      id: test
      name: ${{ matrix.runtime }} E2E test (Java ${{ matrix.java }})
      run: 'docker run --rm \

        -v /var/run/docker.sock:/var/run/docker.sock \

        -v $PWD/$REPORT_DIR:/hawtio-test-suite/tests/hawtio-test-suite/target \

        -v $PWD/$REPORT_DIR/build:/hawtio-test-suite/tests/hawtio-test-suite/build/
        \

        --shm-size="2g" \

        hawtio-test-suite:${{ matrix.java }} -Pe2e-${{ matrix.runtime }} -Dselenide.browser=${{
        matrix.browser }} \

        -Dio.hawt.test.docker.image=hawtio-${{ matrix.runtime }}-app:${{ matrix.java
        }}

        '
    - continue-on-error: true
      if: always()
      name: Prepare report artifacts
      run: "mkdir -p results/$REPORT_DIR/\ncp $REPORT_DIR/cucumber-reports/* results/$REPORT_DIR/\
        \ \nls $REPORT_DIR/cucumber-reports/\n"
    - continue-on-error: true
      if: always()
      name: Archive test artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.runtime }}-java-${{ matrix.java }}-${{ matrix.browser
          }}
        path: '${{ env.REPORT_DIR }}/build/reports/tests/*.png

          ${{ env.REPORT_DIR }}/*.log

          ${{ env.REPORT_DIR }}/cucumber-reports/*

          '
    - continue-on-error: true
      if: always()
      name: Archive failed test reports
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: 'results/**/*

          '
    strategy:
      fail-fast: false
      matrix:
        browser:
        - firefox
        java:
        - '17'
        - '21'
        runtime:
        - quarkus
        - springboot
name: E2E Test
on:
  repository_dispatch:
    types: trigger-ga___e2e_test.yml
