jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9
      with:
        days-before-close: 14
        days-before-stale: 365
        exempt-issue-labels: status/never-stale
        exempt-pr-labels: status/never-stale
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: status/stale
        stale-issue-message: "This issue has been automatically marked as stale due\
          \ to a year of inactivity.\nIt will be closed if no further activity occurs\
          \ within 14 days.\nIf you think that\u2019s incorrect or the issue should\
          \ never stale, please simply write any comment.\nThanks for your contributions!\n"
        stale-pr-label: status/stale
        stale-pr-message: "This PR has been automatically marked as stale due to a\
          \ year of inactivity.\nIt will be closed if no further activity occurs within\
          \ 14 days.\nIf you think that\u2019s incorrect or the issue should never\
          \ stale, please simply write any comment.\nThanks for your contributions!\n"
name: Stale
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
